const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Particles,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Tween,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Browser.Acts.GoBack,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.Touch.Cnds.OnDoubleTapGestureObject,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.Wait
	];
};
self.C3_JsPropNameTable = [
	{vakl: 0},
	{vixod: 0},
	{vkl: 0},
	{vMenu: 0},
	{kak_igrat: 0},
	{naMenu: 0},
	{naYroven_1: 0},
	{predyprezdenie: 0},
	{raz: 0},
	{restrt: 0},
	{sver: 0},
	{fon_kakigrat: 0},
	{fon_menu: 0},
	{tash: 0},
	{audio: 0},
	{obYsroistve: 0},
	{brauzer: 0},
	{kod: 0},
	{dobavit: 0},
	{klava: 0},
	{ki_1: 0},
	{ki_2: 0},
	{ki_3: 0},
	{ki_4: 0},
	{ki_5: 0},
	{ki_6: 0},
	{ki_7: 0},
	{ki_8: 0},
	{ki_9: 0},
	{ki_10: 0},
	{dl_1: 0},
	{dl_2: 0},
	{dl_3: 0},
	{dl_4: 0},
	{dl_5: 0},
	{dl_6: 0},
	{dl_7: 0},
	{dl_8: 0},
	{dl_9: 0},
	{dl_10: 0},
	{zvezv: 0},
	{zvezv_: 0},
	{zvez_1: 0},
	{zvez_2: 0},
	{ki_11: 0},
	{ki_12: 0},
	{ki_13: 0},
	{ki_14: 0},
	{ki_15: 0},
	{ki_16: 0},
	{ki_17: 0},
	{ki_18: 0},
	{ki_19: 0},
	{ki_20: 0},
	{dl_11: 0},
	{dl_12: 0},
	{dl_13: 0},
	{dl_14: 0},
	{dl_15: 0},
	{dl_16: 0},
	{dl_17: 0},
	{dl_18: 0},
	{dl_19: 0},
	{dl_20: 0},
	{Перетаскивание2: 0},
	{ki: 0},
	{Твинанимация: 0},
	{dl: 0},
	{zvyk: 0},
	{zekra: 0},
	{shet: 0},
	{demo: 0},
	{tri: 0}
];

self.InstanceType = {
	vakl: class extends self.ISpriteInstance {},
	vixod: class extends self.ISpriteInstance {},
	vkl: class extends self.ISpriteInstance {},
	vMenu: class extends self.ISpriteInstance {},
	kak_igrat: class extends self.ISpriteInstance {},
	naMenu: class extends self.ISpriteInstance {},
	naYroven_1: class extends self.ISpriteInstance {},
	predyprezdenie: class extends self.ISpriteInstance {},
	raz: class extends self.ISpriteInstance {},
	restrt: class extends self.ISpriteInstance {},
	sver: class extends self.ISpriteInstance {},
	fon_kakigrat: class extends self.ISpriteInstance {},
	fon_menu: class extends self.ISpriteInstance {},
	tash: class extends self.IInstance {},
	audio: class extends self.IInstance {},
	obYsroistve: class extends self.IInstance {},
	brauzer: class extends self.IInstance {},
	kod: class extends self.ISpriteInstance {},
	dobavit: class extends self.ISpriteInstance {},
	klava: class extends self.IInstance {},
	ki_1: class extends self.ISpriteInstance {},
	ki_2: class extends self.ISpriteInstance {},
	ki_3: class extends self.ISpriteInstance {},
	ki_4: class extends self.ISpriteInstance {},
	ki_5: class extends self.ISpriteInstance {},
	ki_6: class extends self.ISpriteInstance {},
	ki_7: class extends self.ISpriteInstance {},
	ki_8: class extends self.ISpriteInstance {},
	ki_9: class extends self.ISpriteInstance {},
	ki_10: class extends self.ISpriteInstance {},
	dl_1: class extends self.ISpriteInstance {},
	dl_2: class extends self.ISpriteInstance {},
	dl_3: class extends self.ISpriteInstance {},
	dl_4: class extends self.ISpriteInstance {},
	dl_5: class extends self.ISpriteInstance {},
	dl_6: class extends self.ISpriteInstance {},
	dl_7: class extends self.ISpriteInstance {},
	dl_8: class extends self.ISpriteInstance {},
	dl_9: class extends self.ISpriteInstance {},
	dl_10: class extends self.ISpriteInstance {},
	zvezv: class extends self.ISpriteInstance {},
	zvezv_: class extends self.ISpriteInstance {},
	zvez_1: class extends self.IParticlesInstance {},
	zvez_2: class extends self.IParticlesInstance {},
	ki_11: class extends self.ISpriteInstance {},
	ki_12: class extends self.ISpriteInstance {},
	ki_13: class extends self.ISpriteInstance {},
	ki_14: class extends self.ISpriteInstance {},
	ki_15: class extends self.ISpriteInstance {},
	ki_16: class extends self.ISpriteInstance {},
	ki_17: class extends self.ISpriteInstance {},
	ki_18: class extends self.ISpriteInstance {},
	ki_19: class extends self.ISpriteInstance {},
	ki_20: class extends self.ISpriteInstance {},
	dl_11: class extends self.ISpriteInstance {},
	dl_12: class extends self.ISpriteInstance {},
	dl_13: class extends self.ISpriteInstance {},
	dl_14: class extends self.ISpriteInstance {},
	dl_15: class extends self.ISpriteInstance {},
	dl_16: class extends self.ISpriteInstance {},
	dl_17: class extends self.ISpriteInstance {},
	dl_18: class extends self.ISpriteInstance {},
	dl_19: class extends self.ISpriteInstance {},
	dl_20: class extends self.ISpriteInstance {},
	ki: class extends self.ISpriteInstance {},
	dl: class extends self.ISpriteInstance {}
}