const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.scrollto,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Browser,
		C3.Behaviors.Sin,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Browser.Acts.GoBack,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Sin.Acts.SetEnabled
	];
};
self.C3_JsPropNameTable = [
	{vakl: 0},
	{vixod: 0},
	{vkl: 0},
	{vMenu: 0},
	{kak_igrat: 0},
	{naMenu: 0},
	{naYroven_1: 0},
	{predyprezdenie: 0},
	{raz: 0},
	{restrt: 0},
	{sver: 0},
	{naYroven_2: 0},
	{naYroven_3: 0},
	{fon_kakigrat: 0},
	{fon_menu: 0},
	{apelsin: 0},
	{baby: 0},
	{derevo: 0},
	{krovat: 0},
	{linia: 0},
	{eda: 0},
	{Твинанимация: 0},
	{СледитьЗа: 0},
	{camera: 0},
	{linia_apelsin_sok: 0},
	{linia_beby_soska: 0},
	{linia_list_derevo: 0},
	{linia_mash_vorota: 0},
	{linia_obliza_shokolad: 0},
	{linia_pribor_eda: 0},
	{linia_sled_sobaka: 0},
	{linia_sneg_snegovik: 0},
	{linia_spit_krovat: 0},
	{list: 0},
	{mash: 0},
	{n1: 0},
	{n2: 0},
	{n3: 0},
	{n4: 0},
	{n5: 0},
	{n6: 0},
	{n7: 0},
	{n8: 0},
	{n9: 0},
	{obliza: 0},
	{podlozka: 0},
	{pribor: 0},
	{shkolad: 0},
	{sled: 0},
	{smail: 0},
	{sneg: 0},
	{snegovik: 0},
	{sobaka: 0},
	{sok: 0},
	{soska: 0},
	{spit: 0},
	{text: 0},
	{vorota: 0},
	{lineika: 0},
	{s1: 0},
	{s2: 0},
	{s3: 0},
	{s4: 0},
	{s5: 0},
	{s6: 0},
	{s7: 0},
	{s8: 0},
	{s9: 0},
	{car: 0},
	{gitara: 0},
	{gyba: 0},
	{kluz: 0},
	{linia_boleet_bolniza: 0},
	{linia_car_trasa: 0},
	{linia_gitara_nota: 0},
	{linia_kluz_zamok: 0},
	{linia_oshki_solnze: 0},
	{linia_shetka_gyba: 0},
	{nota: 0},
	{trasa: 0},
	{zamok: 0},
	{oshki: 0},
	{shetka: 0},
	{solnze: 0},
	{tysha: 0},
	{zont: 0},
	{boleet: 0},
	{bolniza: 0},
	{ded: 0},
	{klys: 0},
	{linia_ded_podarok: 0},
	{linia_klys_remontnik: 0},
	{linia_tysha_zont: 0},
	{podarok: 0},
	{remontnik: 0},
	{tash: 0},
	{audio: 0},
	{obYsroistve: 0},
	{brauzer: 0},
	{kod: 0},
	{Emoji: 0},
	{Синусоида: 0},
	{kartinki: 0},
	{zvyk: 0},
	{zekra: 0},
	{shet: 0},
	{demo: 0},
	{X: 0},
	{Y: 0},
	{xDistans: 0},
	{MaxDistans: 0},
	{Начальная: 0},
	{Конечная: 0}
];

self.InstanceType = {
	vakl: class extends self.ISpriteInstance {},
	vixod: class extends self.ISpriteInstance {},
	vkl: class extends self.ISpriteInstance {},
	vMenu: class extends self.ISpriteInstance {},
	kak_igrat: class extends self.ISpriteInstance {},
	naMenu: class extends self.ISpriteInstance {},
	naYroven_1: class extends self.ISpriteInstance {},
	predyprezdenie: class extends self.ISpriteInstance {},
	raz: class extends self.ISpriteInstance {},
	restrt: class extends self.ISpriteInstance {},
	sver: class extends self.ISpriteInstance {},
	naYroven_2: class extends self.ISpriteInstance {},
	naYroven_3: class extends self.ISpriteInstance {},
	fon_kakigrat: class extends self.ISpriteInstance {},
	fon_menu: class extends self.ISpriteInstance {},
	apelsin: class extends self.ISpriteInstance {},
	baby: class extends self.ISpriteInstance {},
	derevo: class extends self.ISpriteInstance {},
	krovat: class extends self.ISpriteInstance {},
	linia: class extends self.ISpriteInstance {},
	eda: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	linia_apelsin_sok: class extends self.ISpriteInstance {},
	linia_beby_soska: class extends self.ISpriteInstance {},
	linia_list_derevo: class extends self.ISpriteInstance {},
	linia_mash_vorota: class extends self.ISpriteInstance {},
	linia_obliza_shokolad: class extends self.ISpriteInstance {},
	linia_pribor_eda: class extends self.ISpriteInstance {},
	linia_sled_sobaka: class extends self.ISpriteInstance {},
	linia_sneg_snegovik: class extends self.ISpriteInstance {},
	linia_spit_krovat: class extends self.ISpriteInstance {},
	list: class extends self.ISpriteInstance {},
	mash: class extends self.ISpriteInstance {},
	n1: class extends self.ISpriteInstance {},
	n2: class extends self.ISpriteInstance {},
	n3: class extends self.ISpriteInstance {},
	n4: class extends self.ISpriteInstance {},
	n5: class extends self.ISpriteInstance {},
	n6: class extends self.ISpriteInstance {},
	n7: class extends self.ISpriteInstance {},
	n8: class extends self.ISpriteInstance {},
	n9: class extends self.ISpriteInstance {},
	obliza: class extends self.ISpriteInstance {},
	podlozka: class extends self.ISpriteInstance {},
	pribor: class extends self.ISpriteInstance {},
	shkolad: class extends self.ISpriteInstance {},
	sled: class extends self.ISpriteInstance {},
	smail: class extends self.ISpriteInstance {},
	sneg: class extends self.ISpriteInstance {},
	snegovik: class extends self.ISpriteInstance {},
	sobaka: class extends self.ISpriteInstance {},
	sok: class extends self.ISpriteInstance {},
	soska: class extends self.ISpriteInstance {},
	spit: class extends self.ISpriteInstance {},
	text: class extends self.ITextInstance {},
	vorota: class extends self.ISpriteInstance {},
	lineika: class extends self.ITiledBackgroundInstance {},
	s1: class extends self.ISpriteInstance {},
	s2: class extends self.ISpriteInstance {},
	s3: class extends self.ISpriteInstance {},
	s4: class extends self.ISpriteInstance {},
	s5: class extends self.ISpriteInstance {},
	s6: class extends self.ISpriteInstance {},
	s7: class extends self.ISpriteInstance {},
	s8: class extends self.ISpriteInstance {},
	s9: class extends self.ISpriteInstance {},
	car: class extends self.ISpriteInstance {},
	gitara: class extends self.ISpriteInstance {},
	gyba: class extends self.ISpriteInstance {},
	kluz: class extends self.ISpriteInstance {},
	linia_boleet_bolniza: class extends self.ISpriteInstance {},
	linia_car_trasa: class extends self.ISpriteInstance {},
	linia_gitara_nota: class extends self.ISpriteInstance {},
	linia_kluz_zamok: class extends self.ISpriteInstance {},
	linia_oshki_solnze: class extends self.ISpriteInstance {},
	linia_shetka_gyba: class extends self.ISpriteInstance {},
	nota: class extends self.ISpriteInstance {},
	trasa: class extends self.ISpriteInstance {},
	zamok: class extends self.ISpriteInstance {},
	oshki: class extends self.ISpriteInstance {},
	shetka: class extends self.ISpriteInstance {},
	solnze: class extends self.ISpriteInstance {},
	tysha: class extends self.ISpriteInstance {},
	zont: class extends self.ISpriteInstance {},
	boleet: class extends self.ISpriteInstance {},
	bolniza: class extends self.ISpriteInstance {},
	ded: class extends self.ISpriteInstance {},
	klys: class extends self.ISpriteInstance {},
	linia_ded_podarok: class extends self.ISpriteInstance {},
	linia_klys_remontnik: class extends self.ISpriteInstance {},
	linia_tysha_zont: class extends self.ISpriteInstance {},
	podarok: class extends self.ISpriteInstance {},
	remontnik: class extends self.ISpriteInstance {},
	tash: class extends self.IInstance {},
	audio: class extends self.IInstance {},
	obYsroistve: class extends self.IInstance {},
	brauzer: class extends self.IInstance {},
	kod: class extends self.ISpriteInstance {},
	Emoji: class extends self.ISpriteInstance {},
	kartinki: class extends self.ISpriteInstance {}
}