const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Browser,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Flash,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.Stop,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Browser.Acts.GoBack,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Behaviors.DragnDrop.Acts.SetEnabled
	];
};
self.C3_JsPropNameTable = [
	{vakl: 0},
	{vixod: 0},
	{vkl: 0},
	{vMenu: 0},
	{kak_igrat: 0},
	{kakIgrat_fon: 0},
	{menu_fon: 0},
	{naMenu: 0},
	{naYroven: 0},
	{predyprezdenie: 0},
	{raz: 0},
	{restrt: 0},
	{sver: 0},
	{klava: 0},
	{tash: 0},
	{audio: 0},
	{obYsroistve: 0},
	{brauzer: 0},
	{kod: 0},
	{bg: 0},
	{dom: 0},
	{k1: 0},
	{k2: 0},
	{k3: 0},
	{k4: 0},
	{k5: 0},
	{k6: 0},
	{d6: 0},
	{d1: 0},
	{d2: 0},
	{d4: 0},
	{d3: 0},
	{d5: 0},
	{dc_6: 0},
	{dc_5: 0},
	{dc_4: 0},
	{dc_3: 0},
	{dc_2: 0},
	{dc_1: 0},
	{vanna: 0},
	{spalna: 0},
	{gostinna: 0},
	{kyxna: 0},
	{komnata: 0},
	{Перетаскивание: 0},
	{mebel: 0},
	{Мигание: 0},
	{mebel_mig: 0},
	{zvyk: 0},
	{zekra: 0},
	{demo: 0},
	{shet: 0}
];

self.InstanceType = {
	vakl: class extends self.ISpriteInstance {},
	vixod: class extends self.ISpriteInstance {},
	vkl: class extends self.ISpriteInstance {},
	vMenu: class extends self.ISpriteInstance {},
	kak_igrat: class extends self.ISpriteInstance {},
	kakIgrat_fon: class extends self.ISpriteInstance {},
	menu_fon: class extends self.ISpriteInstance {},
	naMenu: class extends self.ISpriteInstance {},
	naYroven: class extends self.ISpriteInstance {},
	predyprezdenie: class extends self.ISpriteInstance {},
	raz: class extends self.ISpriteInstance {},
	restrt: class extends self.ISpriteInstance {},
	sver: class extends self.ISpriteInstance {},
	klava: class extends self.IInstance {},
	tash: class extends self.IInstance {},
	audio: class extends self.IInstance {},
	obYsroistve: class extends self.IInstance {},
	brauzer: class extends self.IInstance {},
	kod: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	dom: class extends self.ISpriteInstance {},
	k1: class extends self.ISpriteInstance {},
	k2: class extends self.ISpriteInstance {},
	k3: class extends self.ISpriteInstance {},
	k4: class extends self.ISpriteInstance {},
	k5: class extends self.ISpriteInstance {},
	k6: class extends self.ISpriteInstance {},
	d6: class extends self.ISpriteInstance {},
	d1: class extends self.ISpriteInstance {},
	d2: class extends self.ISpriteInstance {},
	d4: class extends self.ISpriteInstance {},
	d3: class extends self.ISpriteInstance {},
	d5: class extends self.ISpriteInstance {},
	dc_6: class extends self.ISpriteInstance {},
	dc_5: class extends self.ISpriteInstance {},
	dc_4: class extends self.ISpriteInstance {},
	dc_3: class extends self.ISpriteInstance {},
	dc_2: class extends self.ISpriteInstance {},
	dc_1: class extends self.ISpriteInstance {},
	vanna: class extends self.ISpriteInstance {},
	spalna: class extends self.ISpriteInstance {},
	gostinna: class extends self.ISpriteInstance {},
	kyxna: class extends self.ISpriteInstance {},
	komnata: class extends self.ISpriteInstance {},
	mebel: class extends self.ISpriteInstance {},
	mebel_mig: class extends self.ISpriteInstance {}
}