const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Pathfinding,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Browser,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Browser.Acts.GoBack,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Acts.Wait
	];
};
self.C3_JsPropNameTable = [
	{vakl: 0},
	{vixod: 0},
	{vkl: 0},
	{vMenu: 0},
	{kak_igrat: 0},
	{naMenu: 0},
	{naYroven_1: 0},
	{predyprezdenie: 0},
	{raz: 0},
	{restrt: 0},
	{sver: 0},
	{naYroven_2: 0},
	{naYroven_3: 0},
	{fon_kakigrat: 0},
	{fon_menu: 0},
	{fon_igra: 0},
	{K1: 0},
	{K2: 0},
	{K3: 0},
	{K4: 0},
	{K5: 0},
	{K6: 0},
	{Твёрдый: 0},
	{blok: 0},
	{kt_1: 0},
	{kt_2: 0},
	{kt_3: 0},
	{kt_4: 0},
	{kt_5: 0},
	{kt_6: 0},
	{light_bulb_: 0},
	{N1: 0},
	{N2: 0},
	{N3: 0},
	{N4: 0},
	{N5: 0},
	{N6: 0},
	{nt_1: 0},
	{nt_2: 0},
	{nt_3: 0},
	{nt_4: 0},
	{nt_5: 0},
	{nt_6: 0},
	{S1: 0},
	{S2: 0},
	{S3: 0},
	{S4: 0},
	{S5: 0},
	{S6: 0},
	{st_1: 0},
	{st_2: 0},
	{st_3: 0},
	{st_4: 0},
	{st_5: 0},
	{st_6: 0},
	{th: 0},
	{ur_: 0},
	{ur_2: 0},
	{ur_3: 0},
	{ПоискПути: 0},
	{zarad: 0},
	{fon_ig: 0},
	{KK_1: 0},
	{KK_2: 0},
	{KK_3: 0},
	{KK_4: 0},
	{KK_5: 0},
	{KK_6: 0},
	{NK_1: 0},
	{NK_2: 0},
	{NK_3: 0},
	{NK_4: 0},
	{NK_5: 0},
	{NK_6: 0},
	{SK_1: 0},
	{SK_2: 0},
	{SK_3: 0},
	{SK_4: 0},
	{SK_5: 0},
	{SK_6: 0},
	{tash: 0},
	{audio: 0},
	{obYsroistve: 0},
	{brauzer: 0},
	{kod: 0},
	{Перетаскивание: 0},
	{provod: 0},
	{zvyk: 0},
	{zekra: 0},
	{shet: 0},
	{demo: 0}
];

self.InstanceType = {
	vakl: class extends self.ISpriteInstance {},
	vixod: class extends self.ISpriteInstance {},
	vkl: class extends self.ISpriteInstance {},
	vMenu: class extends self.ISpriteInstance {},
	kak_igrat: class extends self.ISpriteInstance {},
	naMenu: class extends self.ISpriteInstance {},
	naYroven_1: class extends self.ISpriteInstance {},
	predyprezdenie: class extends self.ISpriteInstance {},
	raz: class extends self.ISpriteInstance {},
	restrt: class extends self.ISpriteInstance {},
	sver: class extends self.ISpriteInstance {},
	naYroven_2: class extends self.ISpriteInstance {},
	naYroven_3: class extends self.ISpriteInstance {},
	fon_kakigrat: class extends self.ISpriteInstance {},
	fon_menu: class extends self.ISpriteInstance {},
	fon_igra: class extends self.ISpriteInstance {},
	K1: class extends self.ISpriteInstance {},
	K2: class extends self.ISpriteInstance {},
	K3: class extends self.ISpriteInstance {},
	K4: class extends self.ISpriteInstance {},
	K5: class extends self.ISpriteInstance {},
	K6: class extends self.ISpriteInstance {},
	blok: class extends self.ISpriteInstance {},
	kt_1: class extends self.ISpriteInstance {},
	kt_2: class extends self.ISpriteInstance {},
	kt_3: class extends self.ISpriteInstance {},
	kt_4: class extends self.ISpriteInstance {},
	kt_5: class extends self.ISpriteInstance {},
	kt_6: class extends self.ISpriteInstance {},
	light_bulb_: class extends self.ISpriteInstance {},
	N1: class extends self.ISpriteInstance {},
	N2: class extends self.ISpriteInstance {},
	N3: class extends self.ISpriteInstance {},
	N4: class extends self.ISpriteInstance {},
	N5: class extends self.ISpriteInstance {},
	N6: class extends self.ISpriteInstance {},
	nt_1: class extends self.ISpriteInstance {},
	nt_2: class extends self.ISpriteInstance {},
	nt_3: class extends self.ISpriteInstance {},
	nt_4: class extends self.ISpriteInstance {},
	nt_5: class extends self.ISpriteInstance {},
	nt_6: class extends self.ISpriteInstance {},
	S1: class extends self.ISpriteInstance {},
	S2: class extends self.ISpriteInstance {},
	S3: class extends self.ISpriteInstance {},
	S4: class extends self.ISpriteInstance {},
	S5: class extends self.ISpriteInstance {},
	S6: class extends self.ISpriteInstance {},
	st_1: class extends self.ISpriteInstance {},
	st_2: class extends self.ISpriteInstance {},
	st_3: class extends self.ISpriteInstance {},
	st_4: class extends self.ISpriteInstance {},
	st_5: class extends self.ISpriteInstance {},
	st_6: class extends self.ISpriteInstance {},
	th: class extends self.ISpriteInstance {},
	ur_: class extends self.ISpriteInstance {},
	ur_2: class extends self.ISpriteInstance {},
	ur_3: class extends self.ISpriteInstance {},
	zarad: class extends self.ISpriteInstance {},
	fon_ig: class extends self.ISpriteInstance {},
	KK_1: class extends self.ISpriteInstance {},
	KK_2: class extends self.ISpriteInstance {},
	KK_3: class extends self.ISpriteInstance {},
	KK_4: class extends self.ISpriteInstance {},
	KK_5: class extends self.ISpriteInstance {},
	KK_6: class extends self.ISpriteInstance {},
	NK_1: class extends self.ISpriteInstance {},
	NK_2: class extends self.ISpriteInstance {},
	NK_3: class extends self.ISpriteInstance {},
	NK_4: class extends self.ISpriteInstance {},
	NK_5: class extends self.ISpriteInstance {},
	NK_6: class extends self.ISpriteInstance {},
	SK_1: class extends self.ISpriteInstance {},
	SK_2: class extends self.ISpriteInstance {},
	SK_3: class extends self.ISpriteInstance {},
	SK_4: class extends self.ISpriteInstance {},
	SK_5: class extends self.ISpriteInstance {},
	SK_6: class extends self.ISpriteInstance {},
	tash: class extends self.IInstance {},
	audio: class extends self.IInstance {},
	obYsroistve: class extends self.IInstance {},
	brauzer: class extends self.IInstance {},
	kod: class extends self.ISpriteInstance {},
	provod: class extends self.ISpriteInstance {}
}