const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Fade,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Browser,
		C3.Behaviors.TileMovement,
		C3.Behaviors.Flash,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.TileMovement.Acts.SetEnabled,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Browser.Acts.GoBack,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Behaviors.TileMovement.Cnds.CanMoveDirection,
		C3.Behaviors.TileMovement.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.Flash.Acts.Flash
	];
};
self.C3_JsPropNameTable = [
	{vakl: 0},
	{vixod: 0},
	{vkl: 0},
	{vMenu: 0},
	{kak_igrat: 0},
	{naMenu: 0},
	{naYroven_1: 0},
	{predyprezdenie: 0},
	{raz: 0},
	{restrt: 0},
	{sver: 0},
	{naYroven_2: 0},
	{naYroven_3: 0},
	{fon: 0},
	{fon_kakigrat: 0},
	{fon_menu: 0},
	{fon_igra: 0},
	{Угасание: 0},
	{zvezda_star: 0},
	{ds_01_1: 0},
	{ds_01_2: 0},
	{ds_01_3: 0},
	{ds_01_4: 0},
	{ds_01_5: 0},
	{ds_01_6: 0},
	{ds_01_7: 0},
	{ds_01_8: 0},
	{ds_01_9: 0},
	{Твёрдый: 0},
	{blokk: 0},
	{BackTile_: 0},
	{N_1: 0},
	{N_2: 0},
	{N_3: 0},
	{N_4: 0},
	{N_5: 0},
	{N_6: 0},
	{N_7: 0},
	{N_8: 0},
	{Ns_01_1: 0},
	{Ns_01_2: 0},
	{Ns_01_3: 0},
	{Ns_01_4: 0},
	{Ns_01_5: 0},
	{Ns_01_6: 0},
	{Ns_01_7: 0},
	{Ns_01_8: 0},
	{s1: 0},
	{s2: 0},
	{s3: 0},
	{s4: 0},
	{s5: 0},
	{s6: 0},
	{s_1: 0},
	{s_2: 0},
	{s_3: 0},
	{s_4: 0},
	{s_5: 0},
	{s_6: 0},
	{s_7: 0},
	{s_8: 0},
	{s_9: 0},
	{n1: 0},
	{n2: 0},
	{n3: 0},
	{n4: 0},
	{n5: 0},
	{n6: 0},
	{k1: 0},
	{k2: 0},
	{k3: 0},
	{k4: 0},
	{k5: 0},
	{k6: 0},
	{K_1: 0},
	{K_2: 0},
	{K_3: 0},
	{K_4: 0},
	{K_5: 0},
	{K_6: 0},
	{K_7: 0},
	{K_8: 0},
	{Kl_01_1: 0},
	{Kl_01_2: 0},
	{Kl_01_3: 0},
	{Kl_01_4: 0},
	{Kl_01_5: 0},
	{Kl_01_6: 0},
	{Kl_01_7: 0},
	{Kl_01_8: 0},
	{kak_: 0},
	{kak_2: 0},
	{kak_3: 0},
	{kak_sobirat: 0},
	{kak_sobirat2: 0},
	{kak_sobirat3: 0},
	{klava: 0},
	{tash: 0},
	{audio: 0},
	{obYsroistve: 0},
	{brauzer: 0},
	{kod: 0},
	{ДвижениеПоКлеткам2: 0},
	{Мигание: 0},
	{kybiki: 0},
	{zvyk: 0},
	{zekra: 0},
	{shet: 0},
	{demo: 0}
];

self.InstanceType = {
	vakl: class extends self.ISpriteInstance {},
	vixod: class extends self.ISpriteInstance {},
	vkl: class extends self.ISpriteInstance {},
	vMenu: class extends self.ISpriteInstance {},
	kak_igrat: class extends self.ISpriteInstance {},
	naMenu: class extends self.ISpriteInstance {},
	naYroven_1: class extends self.ISpriteInstance {},
	predyprezdenie: class extends self.ISpriteInstance {},
	raz: class extends self.ISpriteInstance {},
	restrt: class extends self.ISpriteInstance {},
	sver: class extends self.ISpriteInstance {},
	naYroven_2: class extends self.ISpriteInstance {},
	naYroven_3: class extends self.ISpriteInstance {},
	fon: class extends self.ISpriteInstance {},
	fon_kakigrat: class extends self.ISpriteInstance {},
	fon_menu: class extends self.ISpriteInstance {},
	fon_igra: class extends self.ISpriteInstance {},
	zvezda_star: class extends self.ISpriteInstance {},
	ds_01_1: class extends self.ISpriteInstance {},
	ds_01_2: class extends self.ISpriteInstance {},
	ds_01_3: class extends self.ISpriteInstance {},
	ds_01_4: class extends self.ISpriteInstance {},
	ds_01_5: class extends self.ISpriteInstance {},
	ds_01_6: class extends self.ISpriteInstance {},
	ds_01_7: class extends self.ISpriteInstance {},
	ds_01_8: class extends self.ISpriteInstance {},
	ds_01_9: class extends self.ISpriteInstance {},
	blokk: class extends self.ISpriteInstance {},
	BackTile_: class extends self.ISpriteInstance {},
	N_1: class extends self.ISpriteInstance {},
	N_2: class extends self.ISpriteInstance {},
	N_3: class extends self.ISpriteInstance {},
	N_4: class extends self.ISpriteInstance {},
	N_5: class extends self.ISpriteInstance {},
	N_6: class extends self.ISpriteInstance {},
	N_7: class extends self.ISpriteInstance {},
	N_8: class extends self.ISpriteInstance {},
	Ns_01_1: class extends self.ISpriteInstance {},
	Ns_01_2: class extends self.ISpriteInstance {},
	Ns_01_3: class extends self.ISpriteInstance {},
	Ns_01_4: class extends self.ISpriteInstance {},
	Ns_01_5: class extends self.ISpriteInstance {},
	Ns_01_6: class extends self.ISpriteInstance {},
	Ns_01_7: class extends self.ISpriteInstance {},
	Ns_01_8: class extends self.ISpriteInstance {},
	s1: class extends self.ISpriteInstance {},
	s2: class extends self.ISpriteInstance {},
	s3: class extends self.ISpriteInstance {},
	s4: class extends self.ISpriteInstance {},
	s5: class extends self.ISpriteInstance {},
	s6: class extends self.ISpriteInstance {},
	s_1: class extends self.ISpriteInstance {},
	s_2: class extends self.ISpriteInstance {},
	s_3: class extends self.ISpriteInstance {},
	s_4: class extends self.ISpriteInstance {},
	s_5: class extends self.ISpriteInstance {},
	s_6: class extends self.ISpriteInstance {},
	s_7: class extends self.ISpriteInstance {},
	s_8: class extends self.ISpriteInstance {},
	s_9: class extends self.ISpriteInstance {},
	n1: class extends self.ISpriteInstance {},
	n2: class extends self.ISpriteInstance {},
	n3: class extends self.ISpriteInstance {},
	n4: class extends self.ISpriteInstance {},
	n5: class extends self.ISpriteInstance {},
	n6: class extends self.ISpriteInstance {},
	k1: class extends self.ISpriteInstance {},
	k2: class extends self.ISpriteInstance {},
	k3: class extends self.ISpriteInstance {},
	k4: class extends self.ISpriteInstance {},
	k5: class extends self.ISpriteInstance {},
	k6: class extends self.ISpriteInstance {},
	K_1: class extends self.ISpriteInstance {},
	K_2: class extends self.ISpriteInstance {},
	K_3: class extends self.ISpriteInstance {},
	K_4: class extends self.ISpriteInstance {},
	K_5: class extends self.ISpriteInstance {},
	K_6: class extends self.ISpriteInstance {},
	K_7: class extends self.ISpriteInstance {},
	K_8: class extends self.ISpriteInstance {},
	Kl_01_1: class extends self.ISpriteInstance {},
	Kl_01_2: class extends self.ISpriteInstance {},
	Kl_01_3: class extends self.ISpriteInstance {},
	Kl_01_4: class extends self.ISpriteInstance {},
	Kl_01_5: class extends self.ISpriteInstance {},
	Kl_01_6: class extends self.ISpriteInstance {},
	Kl_01_7: class extends self.ISpriteInstance {},
	Kl_01_8: class extends self.ISpriteInstance {},
	kak_: class extends self.ISpriteInstance {},
	kak_2: class extends self.ISpriteInstance {},
	kak_3: class extends self.ISpriteInstance {},
	kak_sobirat: class extends self.ISpriteInstance {},
	kak_sobirat2: class extends self.ISpriteInstance {},
	kak_sobirat3: class extends self.ISpriteInstance {},
	klava: class extends self.IInstance {},
	tash: class extends self.IInstance {},
	audio: class extends self.IInstance {},
	obYsroistve: class extends self.IInstance {},
	brauzer: class extends self.IInstance {},
	kod: class extends self.ISpriteInstance {},
	kybiki: class extends self.ISpriteInstance {}
}