const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Browser,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Tween,
		C3.Behaviors.bound,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Browser.Acts.GoBack,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Browser.Acts.GoToURLWindow
	];
};
self.C3_JsPropNameTable = [
	{vakl: 0},
	{vixod: 0},
	{vkl: 0},
	{vMenu: 0},
	{kak_igrat: 0},
	{kakIgrat_fon: 0},
	{menu_fon: 0},
	{naMenu: 0},
	{naYroven_1: 0},
	{predyprezdenie: 0},
	{raz: 0},
	{restrt: 0},
	{sver: 0},
	{naYroven_2: 0},
	{naYroven_3: 0},
	{fon_game_1: 0},
	{fon_nazalo: 0},
	{fon_game_2: 0},
	{fon_game_3: 0},
	{e1: 0},
	{e2: 0},
	{e3: 0},
	{e4: 0},
	{e5: 0},
	{e6: 0},
	{ferma_1: 0},
	{ferma_2: 0},
	{ferma_3: 0},
	{g1: 0},
	{g2: 0},
	{g3: 0},
	{g4: 0},
	{g5: 0},
	{g6: 0},
	{k1: 0},
	{k2: 0},
	{k3: 0},
	{k4: 0},
	{k5: 0},
	{k6: 0},
	{les_1: 0},
	{les_2: 0},
	{les_3: 0},
	{more_1: 0},
	{more_2: 0},
	{more_3: 0},
	{p1: 0},
	{p2: 0},
	{p3: 0},
	{p4: 0},
	{p5: 0},
	{p6: 0},
	{s1: 0},
	{s2: 0},
	{s3: 0},
	{s4: 0},
	{s5: 0},
	{s6: 0},
	{w1: 0},
	{w2: 0},
	{w3: 0},
	{w4: 0},
	{w5: 0},
	{w6: 0},
	{klava: 0},
	{tash: 0},
	{audio: 0},
	{obYsroistve: 0},
	{brauzer: 0},
	{kod: 0},
	{Перетаскивание: 0},
	{Твинанимация: 0},
	{ОграничитьСценой: 0},
	{famely: 0},
	{zvyk: 0},
	{zekra: 0},
	{shet: 0},
	{demo: 0}
];

self.InstanceType = {
	vakl: class extends self.ISpriteInstance {},
	vixod: class extends self.ISpriteInstance {},
	vkl: class extends self.ISpriteInstance {},
	vMenu: class extends self.ISpriteInstance {},
	kak_igrat: class extends self.ISpriteInstance {},
	kakIgrat_fon: class extends self.ISpriteInstance {},
	menu_fon: class extends self.ISpriteInstance {},
	naMenu: class extends self.ISpriteInstance {},
	naYroven_1: class extends self.ISpriteInstance {},
	predyprezdenie: class extends self.ISpriteInstance {},
	raz: class extends self.ISpriteInstance {},
	restrt: class extends self.ISpriteInstance {},
	sver: class extends self.ISpriteInstance {},
	naYroven_2: class extends self.ISpriteInstance {},
	naYroven_3: class extends self.ISpriteInstance {},
	fon_game_1: class extends self.ISpriteInstance {},
	fon_nazalo: class extends self.ISpriteInstance {},
	fon_game_2: class extends self.ISpriteInstance {},
	fon_game_3: class extends self.ISpriteInstance {},
	e1: class extends self.ISpriteInstance {},
	e2: class extends self.ISpriteInstance {},
	e3: class extends self.ISpriteInstance {},
	e4: class extends self.ISpriteInstance {},
	e5: class extends self.ISpriteInstance {},
	e6: class extends self.ISpriteInstance {},
	ferma_1: class extends self.ISpriteInstance {},
	ferma_2: class extends self.ISpriteInstance {},
	ferma_3: class extends self.ISpriteInstance {},
	g1: class extends self.ISpriteInstance {},
	g2: class extends self.ISpriteInstance {},
	g3: class extends self.ISpriteInstance {},
	g4: class extends self.ISpriteInstance {},
	g5: class extends self.ISpriteInstance {},
	g6: class extends self.ISpriteInstance {},
	k1: class extends self.ISpriteInstance {},
	k2: class extends self.ISpriteInstance {},
	k3: class extends self.ISpriteInstance {},
	k4: class extends self.ISpriteInstance {},
	k5: class extends self.ISpriteInstance {},
	k6: class extends self.ISpriteInstance {},
	les_1: class extends self.ISpriteInstance {},
	les_2: class extends self.ISpriteInstance {},
	les_3: class extends self.ISpriteInstance {},
	more_1: class extends self.ISpriteInstance {},
	more_2: class extends self.ISpriteInstance {},
	more_3: class extends self.ISpriteInstance {},
	p1: class extends self.ISpriteInstance {},
	p2: class extends self.ISpriteInstance {},
	p3: class extends self.ISpriteInstance {},
	p4: class extends self.ISpriteInstance {},
	p5: class extends self.ISpriteInstance {},
	p6: class extends self.ISpriteInstance {},
	s1: class extends self.ISpriteInstance {},
	s2: class extends self.ISpriteInstance {},
	s3: class extends self.ISpriteInstance {},
	s4: class extends self.ISpriteInstance {},
	s5: class extends self.ISpriteInstance {},
	s6: class extends self.ISpriteInstance {},
	w1: class extends self.ISpriteInstance {},
	w2: class extends self.ISpriteInstance {},
	w3: class extends self.ISpriteInstance {},
	w4: class extends self.ISpriteInstance {},
	w5: class extends self.ISpriteInstance {},
	w6: class extends self.ISpriteInstance {},
	klava: class extends self.IInstance {},
	tash: class extends self.IInstance {},
	audio: class extends self.IInstance {},
	obYsroistve: class extends self.IInstance {},
	brauzer: class extends self.IInstance {},
	kod: class extends self.ISpriteInstance {},
	famely: class extends self.ISpriteInstance {}
}