const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.TileMovement,
		C3.Behaviors.bound,
		C3.Behaviors.Tween,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Browser,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Sin,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.TileMovement.Acts.SetEnabled,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Browser.Acts.GoBack,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.TileMovement.Acts.SimulateControl,
		C3.Behaviors.TileMovement.Cnds.IsMoving,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.TileMovement.Acts.SetGridPosition
	];
};
self.C3_JsPropNameTable = [
	{vakl: 0},
	{vixod: 0},
	{vkl: 0},
	{vMenu: 0},
	{kak_igrat: 0},
	{naMenu: 0},
	{naYroven_1: 0},
	{predyprezdenie: 0},
	{raz: 0},
	{restrt: 0},
	{sver: 0},
	{naYroven_2: 0},
	{naYroven_3: 0},
	{fon_kakirat: 0},
	{fon_menu: 0},
	{fon_nazalo: 0},
	{appl: 0},
	{Твёрдый: 0},
	{appl2: 0},
	{appl4: 0},
	{appl5: 0},
	{ДвижениеПоКлеткам: 0},
	{ОграничитьСценой: 0},
	{tank_hero: 0},
	{Твинанимация: 0},
	{sled_G: 0},
	{levo: 0},
	{pravo: 0},
	{vniz: 0},
	{vverx: 0},
	{sled_V: 0},
	{appl6: 0},
	{appl3: 0},
	{appl7: 0},
	{appl8: 0},
	{ts: 0},
	{ts2: 0},
	{ts3: 0},
	{ts4: 0},
	{ts5: 0},
	{ts6: 0},
	{ts7: 0},
	{ts8: 0},
	{s: 0},
	{s2: 0},
	{s3: 0},
	{s4: 0},
	{s5: 0},
	{s6: 0},
	{s7: 0},
	{s8: 0},
	{n: 0},
	{n2: 0},
	{n3: 0},
	{n4: 0},
	{n5: 0},
	{n6: 0},
	{n7: 0},
	{n8: 0},
	{k: 0},
	{k2: 0},
	{k3: 0},
	{k4: 0},
	{k5: 0},
	{k6: 0},
	{tk: 0},
	{tk2: 0},
	{tk3: 0},
	{tk4: 0},
	{tk5: 0},
	{tk6: 0},
	{klava: 0},
	{tash: 0},
	{audio: 0},
	{obYsroistve: 0},
	{brauzer: 0},
	{kod: 0},
	{tileGrass_roadNorth: 0},
	{tileGrass: 0},
	{tileGrass_roadCrossing: 0},
	{tileGrass_roadSplitS: 0},
	{tileGrass_roadCornerUL: 0},
	{tileGrass_roadCornerLR: 0},
	{tileGrass_roadCornerUL2: 0},
	{tileGrass_roadCornerUR: 0},
	{tileGrass_roadCornerLL: 0},
	{tileGrass_roadCornerUR2: 0},
	{Пуля: 0},
	{УничтожениеВнеМакета: 0},
	{bulletBlue2_outline: 0},
	{panel: 0},
	{vistrel: 0},
	{treeGreen_large: 0},
	{treeGreen_small: 0},
	{sandbagBeige: 0},
	{treeGreen_twigs: 0},
	{crateWood1: 0},
	{barrelBlack_top: 0},
	{oilSpill_large: 0},
	{barrelBlack_side: 0},
	{specialBarrel2_outline: 0},
	{wireCrooked: 0},
	{barrelGreen_top: 0},
	{specialBarrel1_outline: 0},
	{wireStraight: 0},
	{fenceRed: 0},
	{tankBody_red_outline: 0},
	{tankRed_barrel2_outline: 0},
	{explosionSmoke: 0},
	{pyla_1: 0},
	{tileSand: 0},
	{tileGrass_roadTransitionN_dirt: 0},
	{tileGrass_roadTransitionN: 0},
	{tileGrass_transitionN: 0},
	{sandbagBrown: 0},
	{tankBody_dark_outline: 0},
	{tankDark_barrel: 0},
	{tracksSmall: 0},
	{barrelRust_top: 0},
	{barrelRust_side: 0},
	{fenceYellow: 0},
	{tileSand_roadCrossing: 0},
	{tileSand_roadNorth: 0},
	{tileSand_roadSplitS: 0},
	{tileSand_roadCornerUR: 0},
	{tileSand_roadCornerLR: 0},
	{tileSand_roadCornerLL: 0},
	{tileSand_roadCornerUL: 0},
	{treeBrown_large: 0},
	{treeBrown_small: 0},
	{treeBrown_twigs: 0},
	{barricadeMetal: 0},
	{Синусоида: 0},
	{specialBarrel3_outline: 0},
	{specialBarrel: 0},
	{crateMetal: 0},
	{barrelGreen_side: 0},
	{pyla_2: 0},
	{oilSpill_small: 0},
	{explosion: 0},
	{thk: 0},
	{thk2: 0},
	{pyla_3: 0},
	{tankBody_blue_outline: 0},
	{tankBlue_barrel2_outline: 0},
	{zvyk: 0},
	{zekra: 0},
	{shet: 0},
	{demo: 0},
	{sles: 0}
];

self.InstanceType = {
	vakl: class extends self.ISpriteInstance {},
	vixod: class extends self.ISpriteInstance {},
	vkl: class extends self.ISpriteInstance {},
	vMenu: class extends self.ISpriteInstance {},
	kak_igrat: class extends self.ISpriteInstance {},
	naMenu: class extends self.ISpriteInstance {},
	naYroven_1: class extends self.ISpriteInstance {},
	predyprezdenie: class extends self.ISpriteInstance {},
	raz: class extends self.ISpriteInstance {},
	restrt: class extends self.ISpriteInstance {},
	sver: class extends self.ISpriteInstance {},
	naYroven_2: class extends self.ISpriteInstance {},
	naYroven_3: class extends self.ISpriteInstance {},
	fon_kakirat: class extends self.ISpriteInstance {},
	fon_menu: class extends self.ISpriteInstance {},
	fon_nazalo: class extends self.ISpriteInstance {},
	appl: class extends self.ISpriteInstance {},
	appl2: class extends self.ISpriteInstance {},
	appl4: class extends self.ISpriteInstance {},
	appl5: class extends self.ISpriteInstance {},
	tank_hero: class extends self.ISpriteInstance {},
	sled_G: class extends self.ISpriteInstance {},
	levo: class extends self.ISpriteInstance {},
	pravo: class extends self.ISpriteInstance {},
	vniz: class extends self.ISpriteInstance {},
	vverx: class extends self.ISpriteInstance {},
	sled_V: class extends self.ISpriteInstance {},
	appl6: class extends self.ISpriteInstance {},
	appl3: class extends self.ISpriteInstance {},
	appl7: class extends self.ISpriteInstance {},
	appl8: class extends self.ISpriteInstance {},
	ts: class extends self.ISpriteInstance {},
	ts2: class extends self.ISpriteInstance {},
	ts3: class extends self.ISpriteInstance {},
	ts4: class extends self.ISpriteInstance {},
	ts5: class extends self.ISpriteInstance {},
	ts6: class extends self.ISpriteInstance {},
	ts7: class extends self.ISpriteInstance {},
	ts8: class extends self.ISpriteInstance {},
	s: class extends self.ISpriteInstance {},
	s2: class extends self.ISpriteInstance {},
	s3: class extends self.ISpriteInstance {},
	s4: class extends self.ISpriteInstance {},
	s5: class extends self.ISpriteInstance {},
	s6: class extends self.ISpriteInstance {},
	s7: class extends self.ISpriteInstance {},
	s8: class extends self.ISpriteInstance {},
	n: class extends self.ISpriteInstance {},
	n2: class extends self.ISpriteInstance {},
	n3: class extends self.ISpriteInstance {},
	n4: class extends self.ISpriteInstance {},
	n5: class extends self.ISpriteInstance {},
	n6: class extends self.ISpriteInstance {},
	n7: class extends self.ISpriteInstance {},
	n8: class extends self.ISpriteInstance {},
	k: class extends self.ISpriteInstance {},
	k2: class extends self.ISpriteInstance {},
	k3: class extends self.ISpriteInstance {},
	k4: class extends self.ISpriteInstance {},
	k5: class extends self.ISpriteInstance {},
	k6: class extends self.ISpriteInstance {},
	tk: class extends self.ISpriteInstance {},
	tk2: class extends self.ISpriteInstance {},
	tk3: class extends self.ISpriteInstance {},
	tk4: class extends self.ISpriteInstance {},
	tk5: class extends self.ISpriteInstance {},
	tk6: class extends self.ISpriteInstance {},
	klava: class extends self.IInstance {},
	tash: class extends self.IInstance {},
	audio: class extends self.IInstance {},
	obYsroistve: class extends self.IInstance {},
	brauzer: class extends self.IInstance {},
	kod: class extends self.ISpriteInstance {},
	tileGrass_roadNorth: class extends self.ISpriteInstance {},
	tileGrass: class extends self.ISpriteInstance {},
	tileGrass_roadCrossing: class extends self.ISpriteInstance {},
	tileGrass_roadSplitS: class extends self.ISpriteInstance {},
	tileGrass_roadCornerUL: class extends self.ISpriteInstance {},
	tileGrass_roadCornerLR: class extends self.ISpriteInstance {},
	tileGrass_roadCornerUL2: class extends self.ISpriteInstance {},
	tileGrass_roadCornerUR: class extends self.ISpriteInstance {},
	tileGrass_roadCornerLL: class extends self.ISpriteInstance {},
	tileGrass_roadCornerUR2: class extends self.ISpriteInstance {},
	bulletBlue2_outline: class extends self.ISpriteInstance {},
	panel: class extends self.ISpriteInstance {},
	vistrel: class extends self.ISpriteInstance {},
	treeGreen_large: class extends self.ISpriteInstance {},
	treeGreen_small: class extends self.ISpriteInstance {},
	sandbagBeige: class extends self.ISpriteInstance {},
	treeGreen_twigs: class extends self.ISpriteInstance {},
	crateWood1: class extends self.ISpriteInstance {},
	barrelBlack_top: class extends self.ISpriteInstance {},
	oilSpill_large: class extends self.ISpriteInstance {},
	barrelBlack_side: class extends self.ISpriteInstance {},
	specialBarrel2_outline: class extends self.ISpriteInstance {},
	wireCrooked: class extends self.ISpriteInstance {},
	barrelGreen_top: class extends self.ISpriteInstance {},
	specialBarrel1_outline: class extends self.ISpriteInstance {},
	wireStraight: class extends self.ISpriteInstance {},
	fenceRed: class extends self.ISpriteInstance {},
	tankBody_red_outline: class extends self.ISpriteInstance {},
	tankRed_barrel2_outline: class extends self.ISpriteInstance {},
	explosionSmoke: class extends self.ISpriteInstance {},
	pyla_1: class extends self.ISpriteInstance {},
	tileSand: class extends self.ISpriteInstance {},
	tileGrass_roadTransitionN_dirt: class extends self.ISpriteInstance {},
	tileGrass_roadTransitionN: class extends self.ISpriteInstance {},
	tileGrass_transitionN: class extends self.ISpriteInstance {},
	sandbagBrown: class extends self.ISpriteInstance {},
	tankBody_dark_outline: class extends self.ISpriteInstance {},
	tankDark_barrel: class extends self.ISpriteInstance {},
	tracksSmall: class extends self.ISpriteInstance {},
	barrelRust_top: class extends self.ISpriteInstance {},
	barrelRust_side: class extends self.ISpriteInstance {},
	fenceYellow: class extends self.ISpriteInstance {},
	tileSand_roadCrossing: class extends self.ISpriteInstance {},
	tileSand_roadNorth: class extends self.ISpriteInstance {},
	tileSand_roadSplitS: class extends self.ISpriteInstance {},
	tileSand_roadCornerUR: class extends self.ISpriteInstance {},
	tileSand_roadCornerLR: class extends self.ISpriteInstance {},
	tileSand_roadCornerLL: class extends self.ISpriteInstance {},
	tileSand_roadCornerUL: class extends self.ISpriteInstance {},
	treeBrown_large: class extends self.ISpriteInstance {},
	treeBrown_small: class extends self.ISpriteInstance {},
	treeBrown_twigs: class extends self.ISpriteInstance {},
	barricadeMetal: class extends self.ISpriteInstance {},
	specialBarrel3_outline: class extends self.ISpriteInstance {},
	specialBarrel: class extends self.ISpriteInstance {},
	crateMetal: class extends self.ISpriteInstance {},
	barrelGreen_side: class extends self.ISpriteInstance {},
	pyla_2: class extends self.ISpriteInstance {},
	oilSpill_small: class extends self.ISpriteInstance {},
	explosion: class extends self.ISpriteInstance {},
	thk: class extends self.ISpriteInstance {},
	thk2: class extends self.ISpriteInstance {},
	pyla_3: class extends self.ISpriteInstance {},
	tankBody_blue_outline: class extends self.ISpriteInstance {},
	tankBlue_barrel2_outline: class extends self.ISpriteInstance {}
}