const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Behaviors.Flash,
		C3.Plugins.TiledBg,
		C3.Behaviors.Bullet,
		C3.Behaviors.wrap,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Browser,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Browser.Acts.GoBack,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Bullet.Acts.Bounce,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.TriggerOnce
	];
};
self.C3_JsPropNameTable = [
	{vakl: 0},
	{vixod: 0},
	{vkl: 0},
	{vMenu: 0},
	{kak_igrat: 0},
	{naMenu: 0},
	{naYroven_1: 0},
	{predyprezdenie: 0},
	{raz: 0},
	{restrt: 0},
	{sver: 0},
	{naYroven_2: 0},
	{naYroven_3: 0},
	{fon_kakirat: 0},
	{fon_menu: 0},
	{fon_nazalo: 0},
	{appl: 0},
	{appl2: 0},
	{appl3: 0},
	{appl4: 0},
	{appl5: 0},
	{appl6: 0},
	{blok: 0},
	{Физика: 0},
	{box: 0},
	{Мигание: 0},
	{box2: 0},
	{fon: 0},
	{Пуля: 0},
	{Заворачивание: 0},
	{head_right: 0},
	{Твинанимация: 0},
	{head_right2: 0},
	{k1: 0},
	{k2: 0},
	{k3: 0},
	{k4: 0},
	{K_appl_k_1: 0},
	{K_appl_k_2: 0},
	{K_appl_k_3: 0},
	{K_appl_k_4: 0},
	{K_appl_k_5: 0},
	{Синусоида: 0},
	{K_appl_k_6: 0},
	{levo: 0},
	{n1: 0},
	{n2: 0},
	{n3: 0},
	{n4: 0},
	{pravo: 0},
	{s1: 0},
	{s2: 0},
	{s3: 0},
	{s4: 0},
	{S_appl_s_1: 0},
	{S_appl_s_2: 0},
	{S_appl_s_3: 0},
	{S_appl_s_4: 0},
	{S_appl_s_5: 0},
	{S_appl_s_6: 0},
	{vniz: 0},
	{vverx: 0},
	{klava: 0},
	{tash: 0},
	{audio: 0},
	{obYsroistve: 0},
	{brauzer: 0},
	{kod: 0},
	{zvyk: 0},
	{zekra: 0},
	{shet: 0},
	{demo: 0}
];

self.InstanceType = {
	vakl: class extends self.ISpriteInstance {},
	vixod: class extends self.ISpriteInstance {},
	vkl: class extends self.ISpriteInstance {},
	vMenu: class extends self.ISpriteInstance {},
	kak_igrat: class extends self.ISpriteInstance {},
	naMenu: class extends self.ISpriteInstance {},
	naYroven_1: class extends self.ISpriteInstance {},
	predyprezdenie: class extends self.ISpriteInstance {},
	raz: class extends self.ISpriteInstance {},
	restrt: class extends self.ISpriteInstance {},
	sver: class extends self.ISpriteInstance {},
	naYroven_2: class extends self.ISpriteInstance {},
	naYroven_3: class extends self.ISpriteInstance {},
	fon_kakirat: class extends self.ISpriteInstance {},
	fon_menu: class extends self.ISpriteInstance {},
	fon_nazalo: class extends self.ISpriteInstance {},
	appl: class extends self.ISpriteInstance {},
	appl2: class extends self.ISpriteInstance {},
	appl3: class extends self.ISpriteInstance {},
	appl4: class extends self.ISpriteInstance {},
	appl5: class extends self.ISpriteInstance {},
	appl6: class extends self.ISpriteInstance {},
	blok: class extends self.ISpriteInstance {},
	box: class extends self.ISpriteInstance {},
	box2: class extends self.ISpriteInstance {},
	fon: class extends self.ITiledBackgroundInstance {},
	head_right: class extends self.ISpriteInstance {},
	head_right2: class extends self.ISpriteInstance {},
	k1: class extends self.ISpriteInstance {},
	k2: class extends self.ISpriteInstance {},
	k3: class extends self.ISpriteInstance {},
	k4: class extends self.ISpriteInstance {},
	K_appl_k_1: class extends self.ISpriteInstance {},
	K_appl_k_2: class extends self.ISpriteInstance {},
	K_appl_k_3: class extends self.ISpriteInstance {},
	K_appl_k_4: class extends self.ISpriteInstance {},
	K_appl_k_5: class extends self.ISpriteInstance {},
	K_appl_k_6: class extends self.ISpriteInstance {},
	levo: class extends self.ISpriteInstance {},
	n1: class extends self.ISpriteInstance {},
	n2: class extends self.ISpriteInstance {},
	n3: class extends self.ISpriteInstance {},
	n4: class extends self.ISpriteInstance {},
	pravo: class extends self.ISpriteInstance {},
	s1: class extends self.ISpriteInstance {},
	s2: class extends self.ISpriteInstance {},
	s3: class extends self.ISpriteInstance {},
	s4: class extends self.ISpriteInstance {},
	S_appl_s_1: class extends self.ISpriteInstance {},
	S_appl_s_2: class extends self.ISpriteInstance {},
	S_appl_s_3: class extends self.ISpriteInstance {},
	S_appl_s_4: class extends self.ISpriteInstance {},
	S_appl_s_5: class extends self.ISpriteInstance {},
	S_appl_s_6: class extends self.ISpriteInstance {},
	vniz: class extends self.ISpriteInstance {},
	vverx: class extends self.ISpriteInstance {},
	klava: class extends self.IInstance {},
	tash: class extends self.IInstance {},
	audio: class extends self.IInstance {},
	obYsroistve: class extends self.IInstance {},
	brauzer: class extends self.IInstance {},
	kod: class extends self.ISpriteInstance {}
}