const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Tween,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Browser.Acts.GoBack,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.Wait
	];
};
self.C3_JsPropNameTable = [
	{vakl: 0},
	{vixod: 0},
	{vkl: 0},
	{vMenu: 0},
	{kak_igrat: 0},
	{naMenu: 0},
	{naYroven_1: 0},
	{predyprezdenie: 0},
	{raz: 0},
	{restrt: 0},
	{sver: 0},
	{fon_menu: 0},
	{botinki_sapogi: 0},
	{byket_otritka: 0},
	{derevna_tonell: 0},
	{divan: 0},
	{dom_plaz: 0},
	{doroga_most: 0},
	{fytbolka: 0},
	{gamak: 0},
	{gazeta_jyrnal: 0},
	{glagol: 0},
	{kafe_les: 0},
	{keda_krossa: 0},
	{kniga_skazka: 0},
	{kofe_tia: 0},
	{korzina_vedro_ashik: 0},
	{kreslo: 0},
	{krovat: 0},
	{kyrisa_maso_riba: 0},
	{lavka: 0},
	{linia: 0},
	{magaz_kino: 0},
	{mash_tryba_igryski: 0},
	{milk_kakao: 0},
	{nos_yxo: 0},
	{paket_mysor_korobka: 0},
	{parkovka_krug: 0},
	{pipl: 0},
	{pismo_zapiska: 0},
	{pizza_piroj_sandvish: 0},
	{podarok_car: 0},
	{pole_pole: 0},
	{ptiza_samolet_kisa: 0},
	{pystina_park: 0},
	{ryki_nogi: 0},
	{san_lyna_star: 0},
	{sapka: 0},
	{shtana: 0},
	{styl: 0},
	{svetofor_kartina_derevo: 0},
	{symka_shemodan_rykzak: 0},
	{syp_kasha_salat: 0},
	{tapki_sandali: 0},
	{tort_konfeta: 0},
	{trassa_gorod: 0},
	{tv_noyt_telefon: 0},
	{voda_sok: 0},
	{volos_lizo: 0},
	{xleb_shokolad_app: 0},
	{z_pyst_1: 0},
	{z_pyst_2: 0},
	{z_pyst_3: 0},
	{tash: 0},
	{audio: 0},
	{obYsroistve: 0},
	{brauzer: 0},
	{kod: 0},
	{klava: 0},
	{Перетаскивание: 0},
	{Твинанимация: 0},
	{kartinki: 0},
	{obvodka: 0},
	{zvyk: 0},
	{zekra: 0},
	{shet: 0},
	{demo: 0},
	{proverka: 0}
];

self.InstanceType = {
	vakl: class extends self.ISpriteInstance {},
	vixod: class extends self.ISpriteInstance {},
	vkl: class extends self.ISpriteInstance {},
	vMenu: class extends self.ISpriteInstance {},
	kak_igrat: class extends self.ISpriteInstance {},
	naMenu: class extends self.ISpriteInstance {},
	naYroven_1: class extends self.ISpriteInstance {},
	predyprezdenie: class extends self.ISpriteInstance {},
	raz: class extends self.ISpriteInstance {},
	restrt: class extends self.ISpriteInstance {},
	sver: class extends self.ISpriteInstance {},
	fon_menu: class extends self.ISpriteInstance {},
	botinki_sapogi: class extends self.ISpriteInstance {},
	byket_otritka: class extends self.ISpriteInstance {},
	derevna_tonell: class extends self.ISpriteInstance {},
	divan: class extends self.ISpriteInstance {},
	dom_plaz: class extends self.ISpriteInstance {},
	doroga_most: class extends self.ISpriteInstance {},
	fytbolka: class extends self.ISpriteInstance {},
	gamak: class extends self.ISpriteInstance {},
	gazeta_jyrnal: class extends self.ISpriteInstance {},
	glagol: class extends self.ISpriteInstance {},
	kafe_les: class extends self.ISpriteInstance {},
	keda_krossa: class extends self.ISpriteInstance {},
	kniga_skazka: class extends self.ISpriteInstance {},
	kofe_tia: class extends self.ISpriteInstance {},
	korzina_vedro_ashik: class extends self.ISpriteInstance {},
	kreslo: class extends self.ISpriteInstance {},
	krovat: class extends self.ISpriteInstance {},
	kyrisa_maso_riba: class extends self.ISpriteInstance {},
	lavka: class extends self.ISpriteInstance {},
	linia: class extends self.ISpriteInstance {},
	magaz_kino: class extends self.ISpriteInstance {},
	mash_tryba_igryski: class extends self.ISpriteInstance {},
	milk_kakao: class extends self.ISpriteInstance {},
	nos_yxo: class extends self.ISpriteInstance {},
	paket_mysor_korobka: class extends self.ISpriteInstance {},
	parkovka_krug: class extends self.ISpriteInstance {},
	pipl: class extends self.ISpriteInstance {},
	pismo_zapiska: class extends self.ISpriteInstance {},
	pizza_piroj_sandvish: class extends self.ISpriteInstance {},
	podarok_car: class extends self.ISpriteInstance {},
	pole_pole: class extends self.ISpriteInstance {},
	ptiza_samolet_kisa: class extends self.ISpriteInstance {},
	pystina_park: class extends self.ISpriteInstance {},
	ryki_nogi: class extends self.ISpriteInstance {},
	san_lyna_star: class extends self.ISpriteInstance {},
	sapka: class extends self.ISpriteInstance {},
	shtana: class extends self.ISpriteInstance {},
	styl: class extends self.ISpriteInstance {},
	svetofor_kartina_derevo: class extends self.ISpriteInstance {},
	symka_shemodan_rykzak: class extends self.ISpriteInstance {},
	syp_kasha_salat: class extends self.ISpriteInstance {},
	tapki_sandali: class extends self.ISpriteInstance {},
	tort_konfeta: class extends self.ISpriteInstance {},
	trassa_gorod: class extends self.ISpriteInstance {},
	tv_noyt_telefon: class extends self.ISpriteInstance {},
	voda_sok: class extends self.ISpriteInstance {},
	volos_lizo: class extends self.ISpriteInstance {},
	xleb_shokolad_app: class extends self.ISpriteInstance {},
	z_pyst_1: class extends self.ISpriteInstance {},
	z_pyst_2: class extends self.ISpriteInstance {},
	z_pyst_3: class extends self.ISpriteInstance {},
	tash: class extends self.IInstance {},
	audio: class extends self.IInstance {},
	obYsroistve: class extends self.IInstance {},
	brauzer: class extends self.IInstance {},
	kod: class extends self.ISpriteInstance {},
	klava: class extends self.IInstance {},
	kartinki: class extends self.ISpriteInstance {},
	obvodka: class extends self.ISpriteInstance {}
}