const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Browser,
		C3.Behaviors.Tween,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Tween.Acts.SetEnabled,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Browser.Acts.GoBack,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Cnds.AngleWithin,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.Wait
	];
};
self.C3_JsPropNameTable = [
	{vakl: 0},
	{vixod: 0},
	{vkl: 0},
	{vMenu: 0},
	{kak_igrat: 0},
	{naMenu: 0},
	{naYroven_1: 0},
	{predyprezdenie: 0},
	{raz: 0},
	{restrt: 0},
	{sver: 0},
	{naYroven_2: 0},
	{naYroven_3: 0},
	{fon_kakigrat: 0},
	{fon_menu: 0},
	{fon_igra: 0},
	{N: 0},
	{N_2: 0},
	{N_3: 0},
	{N_4: 0},
	{N_5: 0},
	{N_6: 0},
	{N_7: 0},
	{nh_1: 0},
	{nh_2: 0},
	{nh_3: 0},
	{nh_4: 0},
	{nh_5: 0},
	{nh_6: 0},
	{nh_7: 0},
	{K_1: 0},
	{K_2: 0},
	{K_3: 0},
	{K_4: 0},
	{K_5: 0},
	{K_6: 0},
	{K_7: 0},
	{sh_1: 0},
	{sh_2: 0},
	{sh_3: 0},
	{sh_4: 0},
	{sh_5: 0},
	{sh_6: 0},
	{sh_7: 0},
	{kh_1: 0},
	{kh_2: 0},
	{kh_3: 0},
	{kh_4: 0},
	{kh_5: 0},
	{kh_6: 0},
	{kh_7: 0},
	{klava: 0},
	{KO_1: 0},
	{KO_2: 0},
	{KO_3: 0},
	{KO_4: 0},
	{KO_5: 0},
	{KO_6: 0},
	{KO_7: 0},
	{pipe: 0},
	{pipe_2: 0},
	{pipe_3: 0},
	{pipe_4: 0},
	{pipe_deco: 0},
	{pipe_deco_K1: 0},
	{pipe_deco_K2: 0},
	{pipe_deco_N: 0},
	{pipe_deco_S: 0},
	{pipe_deco_S2: 0},
	{BackTile_2: 0},
	{tash: 0},
	{audio: 0},
	{obYsroistve: 0},
	{brauzer: 0},
	{kod: 0},
	{Твинанимация: 0},
	{Семья1: 0},
	{zvyk: 0},
	{zekra: 0},
	{shet: 0},
	{demo: 0}
];

self.InstanceType = {
	vakl: class extends self.ISpriteInstance {},
	vixod: class extends self.ISpriteInstance {},
	vkl: class extends self.ISpriteInstance {},
	vMenu: class extends self.ISpriteInstance {},
	kak_igrat: class extends self.ISpriteInstance {},
	naMenu: class extends self.ISpriteInstance {},
	naYroven_1: class extends self.ISpriteInstance {},
	predyprezdenie: class extends self.ISpriteInstance {},
	raz: class extends self.ISpriteInstance {},
	restrt: class extends self.ISpriteInstance {},
	sver: class extends self.ISpriteInstance {},
	naYroven_2: class extends self.ISpriteInstance {},
	naYroven_3: class extends self.ISpriteInstance {},
	fon_kakigrat: class extends self.ISpriteInstance {},
	fon_menu: class extends self.ISpriteInstance {},
	fon_igra: class extends self.ISpriteInstance {},
	N: class extends self.ISpriteInstance {},
	N_2: class extends self.ISpriteInstance {},
	N_3: class extends self.ISpriteInstance {},
	N_4: class extends self.ISpriteInstance {},
	N_5: class extends self.ISpriteInstance {},
	N_6: class extends self.ISpriteInstance {},
	N_7: class extends self.ISpriteInstance {},
	nh_1: class extends self.ISpriteInstance {},
	nh_2: class extends self.ISpriteInstance {},
	nh_3: class extends self.ISpriteInstance {},
	nh_4: class extends self.ISpriteInstance {},
	nh_5: class extends self.ISpriteInstance {},
	nh_6: class extends self.ISpriteInstance {},
	nh_7: class extends self.ISpriteInstance {},
	K_1: class extends self.ISpriteInstance {},
	K_2: class extends self.ISpriteInstance {},
	K_3: class extends self.ISpriteInstance {},
	K_4: class extends self.ISpriteInstance {},
	K_5: class extends self.ISpriteInstance {},
	K_6: class extends self.ISpriteInstance {},
	K_7: class extends self.ISpriteInstance {},
	sh_1: class extends self.ISpriteInstance {},
	sh_2: class extends self.ISpriteInstance {},
	sh_3: class extends self.ISpriteInstance {},
	sh_4: class extends self.ISpriteInstance {},
	sh_5: class extends self.ISpriteInstance {},
	sh_6: class extends self.ISpriteInstance {},
	sh_7: class extends self.ISpriteInstance {},
	kh_1: class extends self.ISpriteInstance {},
	kh_2: class extends self.ISpriteInstance {},
	kh_3: class extends self.ISpriteInstance {},
	kh_4: class extends self.ISpriteInstance {},
	kh_5: class extends self.ISpriteInstance {},
	kh_6: class extends self.ISpriteInstance {},
	kh_7: class extends self.ISpriteInstance {},
	klava: class extends self.IInstance {},
	KO_1: class extends self.ISpriteInstance {},
	KO_2: class extends self.ISpriteInstance {},
	KO_3: class extends self.ISpriteInstance {},
	KO_4: class extends self.ISpriteInstance {},
	KO_5: class extends self.ISpriteInstance {},
	KO_6: class extends self.ISpriteInstance {},
	KO_7: class extends self.ISpriteInstance {},
	pipe: class extends self.ISpriteInstance {},
	pipe_2: class extends self.ISpriteInstance {},
	pipe_3: class extends self.ISpriteInstance {},
	pipe_4: class extends self.ISpriteInstance {},
	pipe_deco: class extends self.ISpriteInstance {},
	pipe_deco_K1: class extends self.ISpriteInstance {},
	pipe_deco_K2: class extends self.ISpriteInstance {},
	pipe_deco_N: class extends self.ISpriteInstance {},
	pipe_deco_S: class extends self.ISpriteInstance {},
	pipe_deco_S2: class extends self.ISpriteInstance {},
	BackTile_2: class extends self.ISpriteInstance {},
	tash: class extends self.IInstance {},
	audio: class extends self.IInstance {},
	obYsroistve: class extends self.IInstance {},
	brauzer: class extends self.IInstance {},
	kod: class extends self.ISpriteInstance {},
	Семья1: class extends self.ISpriteInstance {}
}