const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.PlatformInfo,
		C3.Behaviors.Flash,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Browser.Acts.GoBack,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.Browser.Acts.GoToURLWindow
	];
};
self.C3_JsPropNameTable = [
	{doska: 0},
	{k1: 0},
	{k2: 0},
	{k3: 0},
	{k4: 0},
	{k5: 0},
	{k6: 0},
	{s1: 0},
	{s2: 0},
	{s3: 0},
	{s4: 0},
	{s5: 0},
	{s6: 0},
	{fom: 0},
	{shast_1: 0},
	{shast_2: 0},
	{shast_3: 0},
	{shast_4: 0},
	{predMenu: 0},
	{iconZvyk: 0},
	{naMenu: 0},
	{naYroven_1: 0},
	{naYroven_2: 0},
	{raz: 0},
	{sver: 0},
	{predyprezdenie: 0},
	{vakl: 0},
	{vixod: 0},
	{vkl: 0},
	{Твинанимация: 0},
	{vmeenuSyrovna: 0},
	{zanovo: 0},
	{fonMenu: 0},
	{fonik: 0},
	{kod: 0},
	{vmenu: 0},
	{proideno: 0},
	{naYroven_3: 0},
	{a1: 0},
	{a2: 0},
	{a3: 0},
	{a4: 0},
	{a5: 0},
	{a6: 0},
	{doska2: 0},
	{e1: 0},
	{e2: 0},
	{e3: 0},
	{e4: 0},
	{e5: 0},
	{e6: 0},
	{fonurov: 0},
	{shastе_1: 0},
	{shastе_2: 0},
	{shastе_3: 0},
	{shastе_4: 0},
	{shastе_5: 0},
	{b1: 0},
	{b2: 0},
	{b3: 0},
	{b4: 0},
	{v1: 0},
	{v2: 0},
	{v3: 0},
	{v4: 0},
	{fon_svist: 0},
	{b5: 0},
	{b6: 0},
	{v5: 0},
	{v6: 0},
	{shastее_1: 0},
	{shastее_2: 0},
	{shastее_3: 0},
	{shastее_4: 0},
	{shastее_5: 0},
	{tash: 0},
	{audio: 0},
	{brayzer: 0},
	{obYsroistve: 0},
	{L_N: 0},
	{Мигание: 0},
	{L_N_obvod: 0},
	{L_S: 0},
	{L_S_obvod: 0},
	{u1: 0},
	{u2: 0},
	{zvyk: 0},
	{zekran: 0},
	{demo: 0}
];

self.InstanceType = {
	doska: class extends self.ISpriteInstance {},
	k1: class extends self.ISpriteInstance {},
	k2: class extends self.ISpriteInstance {},
	k3: class extends self.ISpriteInstance {},
	k4: class extends self.ISpriteInstance {},
	k5: class extends self.ISpriteInstance {},
	k6: class extends self.ISpriteInstance {},
	s1: class extends self.ISpriteInstance {},
	s2: class extends self.ISpriteInstance {},
	s3: class extends self.ISpriteInstance {},
	s4: class extends self.ISpriteInstance {},
	s5: class extends self.ISpriteInstance {},
	s6: class extends self.ISpriteInstance {},
	fom: class extends self.ISpriteInstance {},
	shast_1: class extends self.ISpriteInstance {},
	shast_2: class extends self.ISpriteInstance {},
	shast_3: class extends self.ISpriteInstance {},
	shast_4: class extends self.ISpriteInstance {},
	predMenu: class extends self.ISpriteInstance {},
	iconZvyk: class extends self.ISpriteInstance {},
	naMenu: class extends self.ISpriteInstance {},
	naYroven_1: class extends self.ISpriteInstance {},
	naYroven_2: class extends self.ISpriteInstance {},
	raz: class extends self.ISpriteInstance {},
	sver: class extends self.ISpriteInstance {},
	predyprezdenie: class extends self.ISpriteInstance {},
	vakl: class extends self.ISpriteInstance {},
	vixod: class extends self.ISpriteInstance {},
	vkl: class extends self.ISpriteInstance {},
	vmeenuSyrovna: class extends self.ISpriteInstance {},
	zanovo: class extends self.ISpriteInstance {},
	fonMenu: class extends self.ISpriteInstance {},
	fonik: class extends self.ISpriteInstance {},
	kod: class extends self.ISpriteInstance {},
	vmenu: class extends self.ISpriteInstance {},
	proideno: class extends self.ISpriteInstance {},
	naYroven_3: class extends self.ISpriteInstance {},
	a1: class extends self.ISpriteInstance {},
	a2: class extends self.ISpriteInstance {},
	a3: class extends self.ISpriteInstance {},
	a4: class extends self.ISpriteInstance {},
	a5: class extends self.ISpriteInstance {},
	a6: class extends self.ISpriteInstance {},
	doska2: class extends self.ISpriteInstance {},
	e1: class extends self.ISpriteInstance {},
	e2: class extends self.ISpriteInstance {},
	e3: class extends self.ISpriteInstance {},
	e4: class extends self.ISpriteInstance {},
	e5: class extends self.ISpriteInstance {},
	e6: class extends self.ISpriteInstance {},
	fonurov: class extends self.ISpriteInstance {},
	shastе_1: class extends self.ISpriteInstance {},
	shastе_2: class extends self.ISpriteInstance {},
	shastе_3: class extends self.ISpriteInstance {},
	shastе_4: class extends self.ISpriteInstance {},
	shastе_5: class extends self.ISpriteInstance {},
	b1: class extends self.ISpriteInstance {},
	b2: class extends self.ISpriteInstance {},
	b3: class extends self.ISpriteInstance {},
	b4: class extends self.ISpriteInstance {},
	v1: class extends self.ISpriteInstance {},
	v2: class extends self.ISpriteInstance {},
	v3: class extends self.ISpriteInstance {},
	v4: class extends self.ISpriteInstance {},
	fon_svist: class extends self.ISpriteInstance {},
	b5: class extends self.ISpriteInstance {},
	b6: class extends self.ISpriteInstance {},
	v5: class extends self.ISpriteInstance {},
	v6: class extends self.ISpriteInstance {},
	shastее_1: class extends self.ISpriteInstance {},
	shastее_2: class extends self.ISpriteInstance {},
	shastее_3: class extends self.ISpriteInstance {},
	shastее_4: class extends self.ISpriteInstance {},
	shastее_5: class extends self.ISpriteInstance {},
	tash: class extends self.IInstance {},
	audio: class extends self.IInstance {},
	brayzer: class extends self.IInstance {},
	obYsroistve: class extends self.IInstance {},
	L_N: class extends self.ISpriteInstance {},
	L_N_obvod: class extends self.ISpriteInstance {},
	L_S: class extends self.ISpriteInstance {},
	L_S_obvod: class extends self.ISpriteInstance {}
}